name: Scheduled Terraform Destroy (Demo Workspace)

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes   # daily at 3 AM UTC
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Terraform Cloud destroy
        run: |
          curl \
            --fail \
            --request POST \
            --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            https://app.terraform.io/api/v2/runs \
            --data '{
              "data": {
                "type": "runs",
                "attributes": {
                  "is-destroy": true,
                  "message": "Scheduled destroy for demo workspace"
                },
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "ws-StZcMS7hgmwUtDKx"
                    }
                  }
                }
              }
            }'

